/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
#include <cmath>
using namespace std;

int main(){
  int pen_term = 1 , last_term = 2, even_sum = 2, limit = 4000000;
  while (last_term <= limit){
    int new_term = pen_term + last_term;
    if (new_term % 2==0){
      even_sum = new_term + even_sum;
    }
    pen_term = last_term;
    last_term = new_term;
    }
  cout << "The sum of the even-valued terms is " << even_sum;
  return 0;
}
